### ISSUE TITLE
Issues installing pyicu

### ISSUE THREAD

**Issue by sgreene570** [openshift-evangelists/ctfd-quickstart#2]
```
Complete output from command python setup.py egg_info:
(running 'icu-config --version')
(running 'pkg-config --modversion icu-i18n')
Package icu-i18n was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-i18n.pc'
to the PKG_CONFIG_PATH environment variable
No package 'icu-i18n' found
Traceback (most recent call last):
File "/tmp/pip-install-jcccaz99/pyicu/setup.py", line 62, in <module>
ICU_VERSION = os.environ['ICU_VERSION']
File "/opt/app-root/lib64/python3.6/os.py", line 669, in __getitem__
raise KeyError(key) from None
KeyError: 'ICU_VERSION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/pip-install-jcccaz99/pyicu/setup.py", line 65, in <module>
ICU_VERSION = check_output(('icu-config', '--version')).strip()
File "/tmp/pip-install-jcccaz99/pyicu/setup.py", line 18, in check_output
return subprocess_check_output(popenargs)
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 403, in run
with Popen(*popenargs, **kwargs) as process:
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 709, in __init__
restore_signals, start_new_session)
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'icu-config': 'icu-config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/pip-install-jcccaz99/pyicu/setup.py", line 68, in <module>
ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()
File "/tmp/pip-install-jcccaz99/pyicu/setup.py", line 18, in check_output
return subprocess_check_output(popenargs)
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 336, in check_output
**kwargs).stdout
File "/opt/rh/rh-python36/root/usr/lib64/python3.6/subprocess.py", line 418, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('pkg-config', '--modversion', 'icu-i18n')' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-jcccaz99/pyicu/setup.py", line 73, in <module>
''')
RuntimeError:
Please set the ICU_VERSION environment variable to the version of
ICU you have installed.

```

**Comment by sgreene570** [comment]
looks like this was fixed in the latest version of ctfd `2.0.5`

**Comment by sgreene570** [comment]
https://github.com/CTFd/CTFd/pull/817

**Comment by sgreene570** [comment]
Can confirm that CTFd is working on this repo by simply changing the release version of ctfd in the corresponding template.

**Comment by nigelh-123** [comment]
I've also been trying to CTFd working in OpenShift (and must confess to being a complete novice!) 
I noticed as above that the version number of CTFd was very old and tried changing to the most recent (2.5.0) but sadly the app would not quite deploy.

Is anyone still using these config files? Or has anything more recent?
